//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD_calc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positive
    {
        public int ID { get; set; }
        public string Char_Pos { get; set; }
        public int Point_Pos { get; set; }
    }
}
